apiVersion: apps/v1
kind: Deployment
metadata:
  name: amir-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amir-app
  template:
    metadata:
      labels:
        app: amir-app
    spec:
      containers:
        - name: amir-app
          image: amir121121/amir-app:latest
          ports:
            - containerPort: 3041
