apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mango.pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "demo-storage"
